# Default initial positions for platform's ros2_control fake system

initial_positions:
  elbow_joint: 0
  shoulder_lift_joint: 0
  shoulder_pan_joint: 0
  wrist_1_joint: 0
  wrist_2_joint: 0
  wrist_3_joint: 0
  # Add the OnRobot 2FG7 gripper joints here
  2fg7_left_finger_joint: 0
  2fg7_right_finger_joint: 0