moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

# FIX: Add controller manager namespace - THIS IS CRITICAL
controller_manager_ns: /controller_manager

moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller
    - onrobot_2fg7_gripper_controller

  joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    allow_trajectory_execution: true
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

  onrobot_2fg7_gripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    allow_trajectory_execution: true
    joints:
      - left_finger_joint
      - right_finger_joint