moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

controller_manager_ns: /controller_manager

moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller
    # Remove onrobot_2fg7_gripper_controller from MoveIt control
    # Gripper will be controlled via onrobot_driver action server

  joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    allow_trajectory_execution: true
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint