moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller
    - onrobot_2fg7_gripper_controller

  joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: joint_trajectory_controller
    default: true
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

  # FIX: Use position controller for gripper instead of trajectory
  onrobot_2fg7_gripper_controller:
    type: FollowJointTrajectory
    action_ns: onrobot_2fg7_gripper_controller
    default: true
    joints:
      - left_finger_joint
      - right_finger_joint