# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    onrobot_2fg7_gripper_controller:
      type: effort_controllers/GripperActionController  # Use effort control

# Arm controller
joint_trajectory_controller:
  ros__parameters:
    joints: 
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: false
    constraints:
      goal_time: 0.0
    state_publish_rate: 50.0
    action_monitor_rate: 20.0

# Gripper controller - EFFORT CONTROL for force/speed control
onrobot_2fg7_gripper_controller:
  ros__parameters:
    joints:
      - left_finger_joint
      - right_finger_joint
    command_interfaces:
      - effort  # CHANGED from position to effort
    state_interfaces:
      - position
      - velocity
      - effort   # ADD effort state interface
    goal_tolerance: 0.01
    stall_velocity_threshold: 0.001
    stall_timeout: 0.5
    action_monitor_rate: 20.0
    state_publish_rate: 50.0
    
    # Effort control specific parameters
    max_effort: 20.0  # Maximum effort/force in N
    
    # PID gains for effort control (adjust these based on your gripper)
    gains:
      left_finger_joint:
        p: 100.0
        i: 0.0
        d: 1.0
      right_finger_joint:
        p: 100.0
        i: 0.0
        d: 1.0