controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    onrobot_2fg7_gripper_controller:
      type: effort_controllers/JointPositionController

# Arm controller
joint_trajectory_controller:
  ros__parameters:
    joints: 
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: false
    constraints:
      goal_time: 0.0
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    action_name: follow_joint_trajectory

# Gripper controller - FIXED: Using effort controller with correct joint mapping
onrobot_2fg7_gripper_controller:
  ros__parameters:
    # Control only the left finger joint (right finger follows via mimic)
    joint: 2fg7_left_finger_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    # Gripper-specific parameters for 35mm-75mm range
    min_position: 0.0      # 35mm total opening (each finger at 0mm)
    max_position: 0.020    # 75mm total opening (each finger at 20mm)
    state_publish_rate: 50.0