controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # REMOVED: onrobot_2fg7_gripper_controller - using onrobot_driver instead

# Arm controller
joint_trajectory_controller:
  ros__parameters:
    joints: 
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: false
    constraints:
      goal_time: 0.0
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    action_name: follow_joint_trajectory

# REMOVED: gripper controller section - using driver instead